title: "My DSRI Workshop Site 2024"
description: "A site made while following along with the GitHub Pages tutorial at DSRI 2024"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
